### PR TITLE
modified background images, logo, btn color and many more

### PR DESCRIPTION
**Pull request by Trojanhell**
These things are modified please go through @Raunaksingh100 -
1. Added "contact us" in the nav bar and link to the contact us section.
2. Changed position navbar items from left to right of the navbar.
3. Added hover effect in the order now button. before hover: white after hover black
4. Relevant images are added in our services section.
5. Designed and changed the logo.
6. Changed the background image of the home page section.
7. Changed background image of our clients section and also color of heading.

Also please tell me if I can contribute in other parts.

### CODE REVIEW

**Review by Raunaksingh100 — COMMENTED** [review]
Can you provide deploy or preview link

**Comment by Trojanhell** [comment]
I am sharing screenshots with you. Which preview link are you talking about.

**Review by Raunaksingh100 — COMMENTED** [review]
plz update your branch

**Comment by Trojanhell** [comment]
Is there anything I have to update?

**Review by Raunaksingh100 — APPROVED** [review]

**Comment by cggvuhh** [comment]
@Trojanhell no need of this you can work on #39 thanks for your contribution

**Pull request closed without merging**
